// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Mūsu Misija"
          descriptions={[
            "Mēs palīdzam cilvēkiem apgūt tehnoloģijas vienkāršā un saprotamā veidā. Key ir izveidots tā, lai pat vislielākie tehnoloģiju iesācēji justos pārliecināti.",
            "Mūsu kursi ir piemēroti ikvienam, kurš vēlas saprast, kā mākslīgais intelekts var uzlabot ikdienas dzīvi un produktivitāti.",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
