// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
        tag="Sazinieties ar mums"
        text="Esat gatavs mācīties? Rakstiet uz e-pastu aleksandrs.grube@gmail.com vai zvaniet +37225449405"
        primaryButton={{"href":"mailto:aleksandrs.grube@gmail.com","text":"Rakstīt e-pastu"}}
        secondaryButton={{"href":"tel:+37225449405","text":"Zvanīt: +37225449405"}}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
