// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Biežāk Uzdotie Jautājumi"
          title="Jums ir jautājumi?"
          description="Mēs esam gatavi atbildēt uz visiem jūsu neskaidrajiem jautājumiem."
          categories={[
            {
              name: "Par kursiem",
              items: [
                {
                  question: "Vai ir vajadzīgas priekšzināšanas?",
                  answer: "Nē, mēs visu izskaidrosim no paša sākuma.",
                },
                {
                  question: "Kā notiek apmaksa?",
                  answer: "Apmaksa notiek ar pārskaitījumu pēc tikšanās vai uz vietas skaidrā naudā.",
                },
              ],
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
