// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesComparison from '@/components/sections/features/FeaturesComparison';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesComparison
          tag="Mūsu Kursu Priekšrocības"
          title="Kāpēc izvēlēties Key?"
          description="Mēs piedāvājam ērtu pieeju, kas pielāgota jūsu vajadzībām un tempam."
          negativeItems={[
            "Nav garlaicīgas teorijas",
            "Nav nepieciešamas priekšzināšanas",
            "Nav sarežģītu terminu",
          ]}
          positiveItems={[
            "Praktiska pieredze",
            "Individuāla pieeja",
            "Vienkāršas pamācības",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
