// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Key AI Kursi"
          title="Apgūstiet Mākslīgo Intelekta Nākotni"
          description="Vienkāršas un saprotamas mācības ikvienam interesentam, izmantojot jaunākās AI tehnoloģijas."
          primaryButton={{
            text: "Uzzināt Vairāk",
            href: "#about",
          }}
          secondaryButton={{
            text: "Cenu Saraksts",
            href: "#pricing",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-abstract-background-with-floating-cyber-particles_1048-14513.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/representation-user-experience-interface-design_23-2150169854.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-cybersecurity-concept-design_23-2151841659.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-key-computer-circuit-board_93675-129578.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-modern-background-with-cyber-particles_1048-12380.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/dreamy-interior-mall_23-2151591484.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
