// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingHighlightedCards from '@/components/sections/pricing/PricingHighlightedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingHighlightedCards
          tag="Mūsu Cenas"
          title="Izvēlieties sev ērtāko veidu"
          description="Skaidri un caurspīdīgi maksājumi par izglītību."
          plans={[
            {
              tag: "Iesācējiem",
              price: "5 €",
              description: "Prezentācija par pamatiem",
              features: [
                "Vienkāršs skaidrojums",
                "Jautājumu sesija",
                "PDF rokasgrāmata",
              ],
              primaryButton: {
                text: "Pieteikties",
                href: "#contact",
              },
            },
            {
              tag: "Populārākais",
              price: "15 €",
              description: "Individuāla Face time sesija",
              features: [
                "Personalizēta palīdzība",
                "Praktiskie uzdevumi",
                "Jautājumu sesija",
              ],
              highlight: "Ieteicams",
              primaryButton: {
                text: "Pieteikties",
                href: "#contact",
              },
            },
            {
              tag: "Profesionāļiem",
              price: "20 €",
              description: "Pilna individuāla tikšanās",
              features: [
                "Padziļināta apmācība",
                "Praktiskais darbs",
                "Materiāli visam gadam",
              ],
              primaryButton: {
                text: "Pieteikties",
                href: "#contact",
              },
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
