// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamGlassCards from '@/components/sections/team/TeamGlassCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamGlassCards
          tag="Mūsu Komanda"
          title="Mācieties no ekspertiem"
          description="Mēs esam šeit, lai palīdzētu jums iepazīt tehnoloģiju pasauli."
          members={[
            {
              name: "Jānis Bērziņš",
              role: "AI Pasniedzējs",
              imageSrc: "http://img.b2bpic.net/free-photo/elderly-woman-with-food-take-away-boxes_1303-26789.jpg",
            },
            {
              name: "Anna Kalniņa",
              role: "Tehnoloģiju Speciāliste",
              imageSrc: "http://img.b2bpic.net/free-photo/handsome-businessman-suit-pointing-fingers-up-smiling-pleased_176420-31711.jpg",
            },
            {
              name: "Pēteris Ozols",
              role: "Konsultants",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-happy-senior-businessman-with-flipchart_1262-1744.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
