// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamGlassCards from '@/components/sections/team/TeamGlassCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamGlassCards
          tag="Mūsu Komanda"
          title="Mācieties no ekspertiem"
          description="Mēs esam šeit, lai palīdzētu jums iepazīt tehnoloģiju pasauli."
          members={[
            {
              name: "Aleksandrs Grūbe",
              role: "CEO, AI pasniedzējs, konsultants",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3JMyOMHkPYwkKDz5B4OkhBFOTDw/uploaded-1789494232369-nbkouutw.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
