// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
        <SectionErrorBoundary name="testimonial">
              <TestimonialMarqueeOverlayCards
          tag="Atsauksmes"
          title="Ko saka mūsu studenti"
          description="Vairāk nekā 100 apmierināti klienti Latvijā."
          testimonials={[
            {
              name: "Marija",
              role: "Pensionāre",
              company: "Key AI",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/expressive-senior-female-posing-indoor_344912-1367.jpg",
            },
            {
              name: "Jānis",
              role: "Iedzīvotājs",
              company: "Key AI",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/go-this-way-cheerful-friendly-looking-male-pensioner-stylish-clothes-pointing-fore-finger-showing-how-get-museum-attractive-senior-man-indicating-wall-with-copyspace-your-text_343059-2700.jpg",
            },
            {
              name: "Dace",
              role: "Mājsaimniece",
              company: "Key AI",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-smiley-woman-home_23-2150062545.jpg",
            },
            {
              name: "Viktors",
              role: "Pensionārs",
              company: "Key AI",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-happy-retired-woman-wearing-cozy-sweater-short-hairdo_343059-1198.jpg",
            },
            {
              name: "Līga",
              role: "Pensionāre",
              company: "Key AI",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-happy-bearded-mature-man-points-index-finger-shows-blank-space_273609-52472.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
