/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Star } from "lucide-react";
import { cls } from "@/lib/utils";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const testimonials = [
  {
    name: "Marija",
    role: "Pensionāre",
    company: "Key AI",
    rating: 5
  },
  {
    name: "Jānis",
    role: "Iedzīvotājs",
    company: "Key AI",
    rating: 5
  },
  {
    name: "Dace",
    role: "Mājsaimniece",
    company: "Key AI",
    rating: 5
  },
  {
    name: "Viktors",
    role: "Pensionārs",
    company: "Key AI",
    rating: 5
  },
  {
    name: "Līga",
    role: "Pensionāre",
    company: "Key AI",
    rating: 5
  }
];

type Testimonial = {
  name: string;
  role: string;
  company: string;
  rating: number;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TestimonialInline = () => {
  const duplicated = [...testimonials, ...testimonials, ...testimonials, ...testimonials];

  return (
    <section aria-label="Testimonials section" className="pt-20 pb-10">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Atsauksmes"}</p>
          </div>

          <TextAnimation
            text={"Ko saka mūsu studenti"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Vairāk nekā 100 apmierināti klienti Latvijā."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="fade-blur">
          <div className="w-content-width mx-auto overflow-hidden mask-fade-x-medium">
            <div className="flex w-max animate-marquee-horizontal" style={{ animationDuration: "60s" }}>
              {duplicated.map((testimonial, i) => (
                <div key={i} className="shrink-0 w-60 md:w-75 2xl:w-80 mb-10 mr-3 md:mr-5 p-5 xl:p-6 card rounded flex flex-col gap-2 justify-between">
                  <div className="flex gap-1.5 mb-1">
                    {Array.from({ length: 5 }).map((_, index) => (
                      <Star
                        key={index}
                        className={cls(
                          "size-5 text-accent",
                          index < testimonial.rating ? "fill-accent" : "fill-transparent"
                        )}
                        strokeWidth={1.5}
                      />
                    ))}
                  </div>

                  <div>
                    <span className="text-xl font-semibold leading-snug block truncate">{testimonial.name}</span>
                    <span className="text-sm text-accent leading-snug block truncate">{testimonial.role} · {testimonial.company}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function TestimonialSection() {
  return (
    <div data-webild-section="testimonial" data-section="testimonial" id="testimonial">
      <TestimonialInline />
    </div>
  );
}
