/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Star } from "lucide-react";
import { cls } from "@/lib/utils";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const testimonials = [
  {
    name: "Marija",
    role: "Pensionāre",
    company: "Key AI",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/expressive-senior-female-posing-indoor_344912-1367.jpg"
  },
  {
    name: "Jānis",
    role: "Iedzīvotājs",
    company: "Key AI",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/go-this-way-cheerful-friendly-looking-male-pensioner-stylish-clothes-pointing-fore-finger-showing-how-get-museum-attractive-senior-man-indicating-wall-with-copyspace-your-text_343059-2700.jpg"
  },
  {
    name: "Dace",
    role: "Mājsaimniece",
    company: "Key AI",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/front-view-smiley-woman-home_23-2150062545.jpg"
  },
  {
    name: "Viktors",
    role: "Pensionārs",
    company: "Key AI",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/beautiful-happy-retired-woman-wearing-cozy-sweater-short-hairdo_343059-1198.jpg"
  },
  {
    name: "Līga",
    role: "Pensionāre",
    company: "Key AI",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-happy-bearded-mature-man-points-index-finger-shows-blank-space_273609-52472.jpg"
  }
];

type Testimonial = {
  name: string;
  role: string;
  company: string;
  rating: number;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TestimonialInline = () => {
  const duplicated = [...testimonials, ...testimonials, ...testimonials, ...testimonials];

  return (
    <section aria-label="Testimonials section" className="pt-20 pb-10">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Atsauksmes"}</p>
          </div>

          <TextAnimation
            text={"Ko saka mūsu studenti"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Vairāk nekā 100 apmierināti klienti Latvijā."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="fade-blur">
          <div className="w-content-width mx-auto overflow-hidden mask-fade-x-medium">
            <div className="flex w-max animate-marquee-horizontal" style={{ animationDuration: "60s" }}>
              {duplicated.map((testimonial, i) => (
                <div key={i} className="relative shrink-0 w-60 md:w-75 2xl:w-80 aspect-4/5 mb-10 mr-3 md:mr-5 rounded overflow-hidden">
                  <ImageOrVideo
                    imageSrc={testimonial.imageSrc}
                    videoSrc={testimonial.videoSrc}
                    className="w-full h-full object-cover"
                  />

                  <div className="absolute inset-x-4 bottom-4 xl:inset-x-5 xl:bottom-5 2xl:inset-x-6 2xl:bottom-6 flex flex-col gap-1 xl:gap-2 2xl:gap-3 p-4 xl:p-5 2xl:p-6 card rounded backdrop-blur-sm">
                    <div className="flex gap-1.5 mb-1">
                      {Array.from({ length: 5 }).map((_, index) => (
                        <Star
                          key={index}
                          className={cls(
                            "size-5 text-accent",
                            index < testimonial.rating ? "fill-accent" : "fill-transparent"
                          )}
                          strokeWidth={1.5}
                        />
                      ))}
                    </div>

                    <span className="text-2xl font-semibold leading-snug truncate">{testimonial.name}</span>

                    <div className="flex flex-col">
                      <span className="text-base leading-snug truncate">{testimonial.role}</span>
                      <span className="text-base leading-snug truncate">{testimonial.company}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function TestimonialSection() {
  return (
    <div data-webild-section="testimonial" data-section="testimonial" id="testimonial">
      <TestimonialInline />
    </div>
  );
}
